### PR TITLE
Support for client side authentication with manual trust evaluation

### PR DESCRIPTION
**Pull request by giedrius-stanevicius**
I added support for client side authentication for my own needs. Thought it also might be usefull for others

### CODE REVIEW

**Comment by Zyphrax** [comment]
It would be great to have this merged in.

**Comment by Umarani516** [comment]
+1 Would be nice to have this merged in. Seems to important for P2P communications.

**Comment by JNApps** [comment]
I have need for this feature as well. I've tested it on my end and everything appears to be working.

**Comment by chrisballinger** [comment]
Would anyone mind writing a test case for this?

**Pull request closed without merging**
