### PR TITLE
Added support for unix domain sockets

### PR DESCRIPTION
**Pull request by jdiehl**
Feature request #76. This is only implemented for GCDAsyncSocket.

Xcode/DomainTest/ demonstrates the use of unix domain sockets as a server and a client.

I tried to implement this feature with as little overall changes to the code as possible, which has yielded some additional code replication.

### CODE REVIEW

**Comment by swt2c** [comment]
@jdiehl Thanks for the unix domain socket support!

I ran into one small bug that was rather tricky to track down (it resulted in connections being accepted on sockets that were closed).  In closeWithError:, this line:
if (!accept4Source && !accept6Source && !readSource && !writeSource)
should also include && !acceptUNSource

**Comment by jdiehl** [comment]
@swt2c Good catch! I have updated my fork

**Comment by chrisballinger** [comment]
@jdiehl Can you rebase your PR against the latest master?

**Comment by jdiehl** [comment]
Thanks for finally finding the the time to consider this. I have updated the pull request.

**Comment by chrisballinger** [comment]
@jdiehl Two small things, would you mind squashing your commits and adding a very basic XCUnit test  to `Tests/CocoaAsyncSocket.xcworkspace` based on the DomainTest example?

Looks awesome, thank you!

**Comment by chrisballinger** [comment]
@jdiehl Thanks! This looks great!

**Comment by jdiehl** [comment]
No problem. In case you haven't noticed - I also extended your generic test cases to verify that actual data transfer worked (I needed this for the unix domain socket tests anyways).

**Comment by chrisballinger** [comment]
@jdiehl Ya great work! Those 'tests' were more of a placeholder so thank you for fixing that up :)

**Comment by chrisballinger** [comment]
@jdiehl Would you mind submitting another PR to fix this failing Travis test? Dunno why this wasn't caught by the tests for the PR itself https://travis-ci.org/robbiehanson/CocoaAsyncSocket/builds/77216073#L564

**Comment by jdiehl** [comment]
The Travis website never seems to finish loading and is not reporting any useful errors for me... Do you see anything?

**Comment by chrisballinger** [comment]
https://gist.github.com/chrisballinger/4c08c6eb34112a6a9ad2

**Comment by jdiehl** [comment]
See #337

**Pull request merged**
