### PR TITLE
support keep socket live even read data time out

### PR DESCRIPTION
**Pull request by myrual**
My application need such feature to read until time out and write next command to tcp socket.

### CODE REVIEW

**Comment by guptatarun84** [comment]
Please help me with, if you could able to achieve GCDAsyncSocket to continue multiple read for around 10 mins before disconnecting the socket.

**Comment by hlung** [comment]
@guptatarun84 I don't understand your problem. Could you explain more?

**Comment by guptatarun84** [comment]
I am implementing P2P chat messaging via Xep-0096, which I could able to implement successfully. But somehow I need to restrict stream initiation message every time once TCP connection is negotiated between two peers. For this I need the socket connection to stay alive for 10 mins during chat conversation. Let me know if you need more info on this.

**Comment by hlung** [comment]
@guptatarun84 I don't see why the socket connection would be cut off... :/ May be you try ping/pong the socket once every 30 sec or something.

**Comment by guptatarun84** [comment]
Yes I have implemented the ping/pong mechanism for XMPP socket connection. But my question is how to restrict SI message to be send everytime while chatting with a peer. It is something where IQ stanza's are exchanging and setting up the direct/proxy connection with peer everytime I send a chat message. Any idea's?

**Comment by guptatarun84** [comment]
I know I could able to achieve this if my readSource keeps on reading the data and able to write at receiver end. But while debugging the GCDAsynSocket I found that it calls closeWithError method once the write is complete for 1st message

**Comment by hlung** [comment]
any helpful error you got from closeWithError?

**Comment by guptatarun84** [comment]
One more thing, to clear the context my ultimate aim is to maintain the SOCKS5 connection once made.

**Comment by myrual** [comment]
What's the error you got ?
2015年2月26日 下午3:45于 "guptatarun84" <notifications@github.com>写道：

**Pull request closed without merging**
