### PR TITLE
runtime workaround for recursive lock crash

### PR DESCRIPTION
**Pull request by silverhammermba**
Potential fix for #803 based on https://juejin.cn/post/7153606703399829511

I have been testing this and while the behavior does not seem to be any worse, it still seems to crash on iOS 16 with the same frequency as before.

### CODE REVIEW

**Comment by calebabm** [comment]
did you have any luck applying the `if (writeStream)` changes in the `- (void)closeWithError:(NSError *)error`? Looks like some others discussed in the comments: https://juejin.cn/post/7153606703399829511

**Comment by silverhammermba** [comment]
@calebabm I was able to completely replace CocoaAsyncSocket in my project, so I am no longer blocked on this crash. feel free to create a new branch incorporating the changes from those comments

**Comment by iMostfa** [comment]
@silverhammermba what did you use instead of CocoaAsyncSocket ?

**Comment by andyliuzs** [comment]
您好我已经收到您的邮件了，待查看后马上回复！

**Comment by silverhammermba** [comment]
@iMostfa I used the built-in [Network](https://developer.apple.com/documentation/network) library to create a `NWConnection` with `NWParameters.tcp`. If you need to support iOS 11 and lower you'll need to use [CFNetwork](https://developer.apple.com/documentation/cfnetwork/) instead.

**Pull request closed without merging**
