### PR TITLE
Fix for sending UDP multicast on IPv6

### PR DESCRIPTION
**Pull request by Umberto73**
This fix adds an API interface to set the network interface on which the multicast datagrams will be sent on. It is needed when sending UDP multicast on IPv6.

This fix was actually suggested by Arno as mentioned in:
https://groups.google.com/forum/#!topic/cocoaasyncsocket/Z9lqXGpR-kU

Huub

### CODE REVIEW

**Comment by chrisballinger** [comment]
@Umberto73 Can you rebase this off the latest master and squash your commits? Thank you!

**Comment by Umberto73** [comment]
Chris, could you be please be more specific on what you want me to do (and why)?

**Comment by RolandasRazma** [comment]
@Umberto73 basically he wants you to resolve conflicts (with latest head) and squash all commits so it would look like 1

**Comment by Umberto73** [comment]
I've resolved the conflicts and committed them. Please verify.

**Comment by dsmurfin** [comment]
@Umberto73 looks like this never made it into the repo. I'm having this problem, so it would be great to see it resolved!

**Comment by chrisballinger** [comment]
@dsmurfin Thanks for bringing this back up! Will take a look.

**Comment by dsmurfin** [comment]
> @dsmurfin Thanks for bringing this back up! Will take a look.

Thanks Chris. I see GitHub actions has closed it again!

**Comment by chrisballinger** [comment]
Bad bot!

**Comment by dsmurfin** [comment]
Hi @chrisballinger it appears GitHub actions has closed this again! This definitely needs to be resolved as it's a bit of a flaw, but I don't have the time at present to put in a pull request myself.

**Comment by chrisballinger** [comment]
Merged via #746

**Pull request closed without merging**
