### PR TITLE
Misc fixes, mostly minor or warning-related

### PR DESCRIPTION
**Pull request by seanm**
- Fixed minor spelling error in comments
- Added __bridge keyword in a few places to pacify Xcode 7 warnings
- Remove a '== YES' since Obj-C BOOL can have 254 different non-zero values
- Replace strcpy() with the safer strlcpy()
- Fixed shadowed variable warning
- Fixed several warnings about repeatedly messaging a weak variable
- Enable several additional compiler warning flags

### CODE REVIEW

**Comment by seanm** [comment]
There's one warning because I added some new warning flags.  I wasn't 100% confident in fixing that warning, so left it for someone that knows the code better.  (There's also a clang static analyzer warning BTW).

**Comment by chrisballinger** [comment]
Rerunning Travis

**Comment by chrisballinger** [comment]
Thanks! I'll review after I get back from vacation

**Comment by seanm** [comment]
@chrisballinger friendly ping...

**Comment by chrisballinger** [comment]
@seanm Whooops sorry, thanks for the reminder! Looks good to me

**Comment by xuchuandong** [comment]
When I use the CocoaAsyncSocket, It cannot connect to server while http can request successfully in the same network, Why？How can I deal with this problem? Very Urgent!

It cannot connect to server,and called the delegate method : 
socketDidDisconnect:<GCDAsyncSocket: 0x10030a180> withError:Error Domain=GCDAsyncSocketErrorDomain Code=3 "Attempt to connect to host timed out" UserInfo={NSLocalizedDescription=Attempt to connect to host timed out}

**Pull request merged**
