### PR TITLE
Add tvOS target

### PR DESCRIPTION
**Pull request by ChaosCoder**
This adds a tvOS target and build scheme, works with carthage now (#362).

### CODE REVIEW

**Comment by ChaosCoder** [comment]
Well, I have nothing to add. Would be great, if you merge it! :)

**Comment by chrisballinger** [comment]
Thank you! :+1:

**Comment by vassifht** [comment]
I'm still getinng: 
[!] The platform of the target `xxx` (tvOS 9.0) is not compatible with `CocoaAsyncSocket (7.4.2)`, which does not support `tvos`.

**Comment by rjgdesign** [comment]
Same, any ideas why?

[!] The platform of the target xxx (tvOS 9.0) is not compatible with CocoaAsyncSocket (7.4.2), which does not support tvos.

**Comment by rubyredrick** [comment]
I'm getting the same thing.

**Comment by creeveliu** [comment]
still the same error by Cocoapods

[!] The platform of the target `xx` (tvOS 9.0) is not compatible with `CocoaAsyncSocket (7.4.2)`, which does not support `tvos`.

**Pull request merged**
