### PR TITLE
Swift package manager

### PR DESCRIPTION
**Pull request by RockLobster**
Adding support for the swift package manager

### CODE REVIEW

**Comment by chrisballinger** [comment]
@RockLobster Thanks! Can you add a `swift build` step to the `.travis.yml`?

**Comment by RockLobster** [comment]
Good one, will do!

**Comment by chrisballinger** [comment]
Looks like the tests might need to be updated:

> ❌  /Users/travis/build/robbiehanson/CocoaAsyncSocket/Tests/Shared/SwiftTests.swift:164:38: overlapping accesses to 'addr', but modification requires exclusive access; consider copying to a local variable
> 742
> 743        withUnsafeMutablePointer(to: &addr) {

**Comment by RockLobster** [comment]
Yeah, it seems that the tests don’t run on Xcode 11 and the old CI was still run on Xcode 9.
I’ll see what I can do

**Comment by chrisballinger** [comment]
@RockLobster Thank you for looking into it!

**Comment by RockLobster** [comment]
I now also added the shared unit tests to SPM, did increase the size of the PR slightly, though

**Pull request merged**
