### PR TITLE
Added MacTarget to Carthage Scheme

### PR DESCRIPTION
**Pull request by jeeftor**
- Added an additional Build target to the project so that Carthage is able to build both an `iOS` target and a `Mac` target.  Updated the travis settings to test the building of the mac target.

Both commands
`carthage build --platform Mac`
`carthage build --platform iOS`

* Updated Project Schemes
* Updated travis CI settings to build both a Mac and an iOS target (to test the frameworks)

### CODE REVIEW

**Comment by izqui** [comment]
Does this result in the iOS and Mac framework having different names? That's why I decided to do the Universal framework as I explain in #345

**Comment by jeeftor** [comment]
They have the same name. Carthage says they don't support universal

**Comment by jeeftor** [comment]
Targets have different name. Fame work same name

**Comment by jeeftor** [comment]
Here is my long winded explanation.  To test this stuff out you can make a `Cartfile` that points to my fork of the repo.  

    #This is the version of my code in the pull request
    github "jeeftor/CocoaAsyncSocket" "master"

Then you can run a  `carthage update` which will then create:

    /Carthage/Build/Mac/CocoaAsyncSocket.framework
    /Carthage/Build/Mac/CocoaAsyncSocket.framework.dSYM
    /Carthage/Build/iOS/CocoaAsyncSocket.framework
    /Carthage/Build/iOS/CocoaAsyncSocket.framework.dSYM


However to get technical I think that the build target name is actually the same as the Scheme name inside of Xcode, and those seem to have to be unique, however, the resultant framework is controlled by the ``PRODUCT_NAME = "$(PROJECT_NAME)";`` item in the build config and as this points to  `$(PROEJCT_NAME)` instead of `$(TARGET_NAME)` its always be called `CocoaAsyncSocket.framework` which is what we want.


So when you run carthage it is going to print out the Target/Scheme names

> *** Fetching CocoaAsyncSocket
> *** Checking out CocoaAsyncSocket at "16f9fd0a620af46293f94919d0670aa91b1b9bb9"
> *** xcodebuild output can be found in /var/folders/ml/mr4ytz0s4rs8n3dgvzwvdn0hkfl0lv/T/carthage-xcodebuild.U4vN5L.log
> *** Building scheme "Mac Framework" in CocoaAsyncSocket.xcodeproj
> *** Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj

which are **Mac Framework** and **iOS Framework**

I considered other Scheme names such as:

* CocoaAsyncSocket iOS 
* CocoaAsyncSocket Mac
 
But i notice inside of Xcode it looked a little nicer if the iOS and Mac came first in case your window wasn't super wide and some of it got truncated you could still see exactly which framework you were working with.

**Comment by jeeftor** [comment]
Updated the documentation to reflect both mac and iOS framework availability

**Comment by jeeftor** [comment]
Any plans to integrate this one?

**Comment by chrisballinger** [comment]
Sorry, it fell off my radar. Looks good, thank you!

**Pull request merged**
