### PR TITLE
Removed a " == YES"

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by seanm** [comment]
Oh, hmmm, seems I can't make a pull request for just the last commit in my fork?

It's really c145766 that should be merged upstream, the rest is GC support stuff.

**Comment by authman** [comment]
Nice commits though. I like your GCDA fork.

**Comment by seanm** [comment]
authman, I'm afraid I don't understand your comment...

**Comment by chrisballinger** [comment]
GC support is deprecated by Apple so not sure if that is good to merge.

**Comment by seanm** [comment]
chrisballinger, could you merge the other parts (excluding the commit related to GC)?

**Comment by seanm** [comment]
@chrisballinger, specifically, could you merge:

https://github.com/seanm/CocoaAsyncSocket/commit/48da28b8dc2e774a9903cb176ddc0e58d7c2a44a
https://github.com/seanm/CocoaAsyncSocket/commit/9747d839ea93600fef347fd1047014a9ffe3bcb7
https://github.com/seanm/CocoaAsyncSocket/commit/0b43d7f4331e7b34d6e03f72a96202c2716cf539

**Comment by chrisballinger** [comment]
Please rebase against master / squash commits and submit a new PR. Thanks!

**Comment by seanm** [comment]
OK, as you wish.

(But isn't it considered bad practice to alter commits that have already to pushed to a public repo?  Do you ask this maybe because github's UI makes it hard to cherry pick by SHA?  I guess so that I don't destroy my own fork's history I could make a branch with only the changes you're likely to merge...)

**Comment by chrisballinger** [comment]
Ya creating a new branch for the PR would be preferable

**Comment by seanm** [comment]
Here you go:  https://github.com/robbiehanson/CocoaAsyncSocket/pull/341

**Pull request closed without merging**
